export const QUESTIONS = [
  "Playing the game was meaningful to me.",
  "The game felt relevant to me.",
  "Playing this game was valuable to me.",
  "I wanted to explore how the game evolved.",
  "I wanted to find out how the game progressed.",
  "I felt eager to discover how the game continued.",
  "I felt I was good at playing this game.",
  "I felt capable while playing the game.",
  "I felt a sense of mastery playing this game.",
  "I felt free to play the game in my own way.",
  "I felt like I had choices regarding how I wanted to play this game.",
  "I felt a sense of freedom about how I wanted to play this game.",
  "I was no longer aware of my surroundings while I was playing.",
  "I was immersed in the game.",
  "I was fully focused on the game.",
  "The game informed me of my progress in the game.",
  "I could easily assess how I was performing in the game.",
  "The game gave clear feedback on my progress towards the goals.",
  "I enjoyed the way the game was styled.",
  "I liked the look and feel of the game.",
  "I appreciated the aesthetics of the game.",
  "The game was not too easy and not too hard to play.",
  "The game was challenging but not too challenging.",
  "The challenges in the game were at the right level of difficulty for me.",
  "It was easy to know how to perform actions in the game.",
  "The actions to control the game were clear to me.",
  "I thought the game was easy to control.",
  "I grasped the overall goal of the game.",
  "The goals of the game were clear to me.",
  "I understood the objectives of the game.",
  "I liked playing the game",
  "The game was entertaining.",
  "I had a good time playing this game.",
];
